title = "Parallel Cat Blog"
copyright = '<a href="about" target="_blank">Mateus Mercer - {year}</a> <br>🌎<br> Tema original por <a href="https://github.com/razonyang/hugo-theme-bootstrap" target="_blank">razonyang</a>'
