dateFormat = "02/01/2006"
description = "Um blog sobre programação, e outras coisas"
keywords = "Tecnologia, Programação, Desenvolvimento, Fullstack"
headerHeadLine = "Um blog sobre programação, e outras coisas"
[archive]
  dateFormat = "01/02"
