dateFormat = "02/01/2006"
description = "Um blog para discutir sobre assuntos diversos de tecnologia"
keywords = "Tecnologia, Programação, Desenvolvimento, Fullstack"
[archive]
  dateFormat = "01/02"
