email = "contact@matbm.net"
#facebook = "yourfacebookusername"
github = "MatMercer"
#gitlab = "yourgitlabusername"
linkedin = "in/matmercer"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
#youtube = "youryoutubechannelid"
#discord = "yourdiscordinvitecode"
#discourse = "https://yourforum.tld"
#facebookgroup = "yourfacebookgroupname"
